config/routes.rb
Web::Application.routes.draw do
  get "jobs/index"
  get "portfolio/chacao"
  get "portfolio/cnti"
  get "portfolio/shick"
  get "portfolio/show"
  get "contact/index"
  devise_for :users

  namespace :admin do
    resources :jobs
  end

  resources :services, only: [:index]
  resources :products, only: [:index]
  resources :portfolio, controller: 'portfolio'
  resource  :company

  root 'welcome#index'
end

app/models/job.rb
class Job < ActiveRecord::Base
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  default_scope -> { order(:created_at) }

  def self.fetch_tweets
    Twitter.user_timeline("DivuxVe", count: 3).each do |t|
      Tweet.where(tweet_id: t.id).first_or_create do |tweet|
        tweet.screen_name = t.user.screen_name
        tweet.content    = t.text
        tweet.tweet_id   = t.id
        tweet.created_at = t.created_at
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable
end

app/controllers/admin/jobs_controller.rb
module Admin
  class JobsController < ApplicationController
    before_action :set_job, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!

    # GET /jobs
    # GET /jobs.json
    def index
      @jobs = Job.all
    end

    # GET /jobs/1
    # GET /jobs/1.json
    def show
    end

    # GET /jobs/new
    def new
      @job = Job.new
    end

    # GET /jobs/1/edit
    def edit
    end

    # POST /jobs
    # POST /jobs.json
    def create
      @job = Job.new(job_params)

      respond_to do |format|
        if @job.save
          format.html { redirect_to [:admin, @job], notice: 'Job was successfully created.' }
        else
          format.html { render action: 'new' }
        end
      end
    end

    # PATCH/PUT /jobs/1
    # PATCH/PUT /jobs/1.json
    def update
      respond_to do |format|
        if @job.update(job_params)
          format.html { redirect_to [:admin, @job], notice: 'Job was successfully updated.' }
        else
          format.html { render action: 'edit' }
        end
      end
    end

    # DELETE /jobs/1
    # DELETE /jobs/1.json
    def destroy
      @job.destroy
      respond_to do |format|
        format.html { redirect_to admin_jobs_url }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_job
        @job = Job.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def job_params
        params.require(:job).permit(:title, :summary, :description)
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def show
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.all
  end
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
  def chacao
  end

  def cnti
  end

  def shick
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def menu_item_class(item)
    'active' if controller_name == item.to_s.pluralize || controller_name == item.to_s
  end
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/views/admin/jobs/_form.html.erb
<%= form_for [:admin, @job], :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :summary, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :summary, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admin_jobs_path, :class => 'btn' %>
  </div>
<% end %>

app/views/admin/jobs/edit.html.erb
<%- model_class = Job -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/jobs/index.html.erb
<%- model_class = Job -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:summary) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= link_to job.id, admin_job_path(job) %></td>
        <td><%= job.title %></td>
        <td><%= job.summary %></td>
        <td><%= job.description %></td>
        <td><%=l job.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_job_path(job), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_job_path(job),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_admin_job_path,
            :class => 'btn btn-primary' %>

app/views/admin/jobs/new.html.erb
<%- model_class = Job -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/jobs/show.html.erb
<%- model_class = Job -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @job.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:summary) %>:</strong></dt>
  <dd><%= @job.summary %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @job.description %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              admin_jobs_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_admin_job_path(@job), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              admin_job_path(@job),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/companies/_company_1.html.erb
<%= image_tag 'about-us/logo-tp.png', alt: 'Trabajo y Persona', class: 'pull-left' %>
<%= link_to 'www.trabajoypersona.org', 'http://www.trabajoypersona.org', class: 'main pull-right' %>

<div class="project-summary">
  <p>
    En Divux afirmamos que "el trabajo es un bien del hombre, porque mediante el trabajo el hombre no solo transforma la naturaleza adaptándola a sus propias necesidades, sino que se realiza como hombre, se hace más hombre"".
  </p>

  <p>
    Compartimos esta concepción que fundamenta el trabajo que hace la Asociación Civil Trabajo y Persona en la difusión del valor de la cultura del trabajo. Por ello, en alianza con esta asociación estamos desarrollando programas de formación en emprendimiento en el sector tecnológico. Porque queremos compartir nuestro conocimiento, generando oportunidades para el desarrollo del emprendimiento en Venezuela.
  </p>
</div>

app/views/companies/_company_2.html.erb
<%= image_tag 'about-us/logo-cdo.png', alt: 'Compañía de las Obras (CDO) Venezuela', class: 'pull-left' %>
<%= link_to 'www.cdo.org.ve', 'http://cdo.org.ve/', class: 'main pull-right' %>

<div class="project-summary">
  <p>
    Divux forma parte de la Asociación CDO Venezuela compartiendo con otras pequeñas, medianas y grandes empresas y ONG’s un mismo criterio sobre la forma de hacer empresa y generando alianzas dentro de la red que la compone.
  </p>

  <p>
    Así mismo ha colaborado en la realización de su portal web, así como en el desarrollo de la plataforma tecnológica que apoya la realización del evento CONTACTO Venezuela.
  </p>
</div>

app/views/companies/_company_3.html.erb
<%= image_tag 'about-us/logo-ucab.png', alt: 'Trabajo y Persona' %>

<div class="project-summary">
  <p>
    CONVENIO UCAB<br>
    En divux estamos comprometidos con la formación de los jóvenes venezolanos, por ello tenemos un convenio de colaboración con el Centro de Investigación de Ingeniería (CIDI) de la Universidad Católica Andrés Bello, con la finalidad de formar a estudiantes en las nuevas tecnologías y darle la oportunidad de realizar proyectos de investigación en conjunto.
  </p>
</div>

app/views/companies/show.html.erb
<div class="about-us">
  <div class="header">
    <div class="container">
      <h1>Nosotros</h1>
    </div>
  </div>

  <div class="summary">
    <div class="container">
      <h2>¿Quiénes Somos?</h2>

      <p>
        Divux nació en el 2007 como resultado del deseo de 3 ingenieros de crear un espacio para desarrollar una
        comunidad de conocimiento que permitiera generar soluciones innovadoras a necesidades detectadas en el
        mercado en el área de las tecnologías móviles.
      </p>

      <p>
        En estos años de trayectoria hemos procurado colocar siempre a la persona y a sus necesidades en el centro
        de nuestra organización. Por eso, para nosotros es fundamental poder responder a nuestros clientes con
        soluciones innovadoras y de calidad.
      </p>

      <p>
        Deseamos ser felices a través del trabajo que hacemos, por eso disfrutarlo y educarnos mientras lo hacemos
        es lo más importante.
      </p>
    </div>
  </div>

  <div class="our-team">
    <%= image_tag 'about-us/our-team.jpg', alt: 'Nuestro Equipo' %>
  </div>
  
  <div class="executive-team">
    <div class="container">
        <h2>Equipo Directivo</h2>
        <div class="boss">
          <a href="http://www.linkedin.com/pub/carlos-alonzo/6/372/673" target="_blank" >LinkedIn Carlos 
           <i></i></a>
          <h5>Carlos Alonzo</h5>
          <p><em>Chief Operating Officer (COO)</em></p>
          <p>Ingeniero en Computación de la Universidad Simón Bolívar (2000), estudios de Postgrado en la Universidad Central de Venezuela en el área de Computación Emergente (IA), Profesor Universitario de la UCAB y tutor industrial de decenas de Pasantías Industriales en el sector.
          Gerente de Sistemas en Conectium Limited Venezuela hasta el 2006, encargado del equipo de desarrollo de software y soporte para diversos proyectos en Latam. En 2007 funda DIVUX junto a sus otros 2 socios y se encarga del área de Tecnología. 
          Actualmente diseña un Programa de Diplomado en Ingeniería de Software para Movilidad, con diversas líneas de investigación que surgen del Departamento de I+D Divux Systems.
          </p>
        </div>
         <div class="boss">
          <a href="http://www.linkedin.com/pub/angel-pacheco/8/649/878" target="_blank" >LinkedIn Ángel
          <i></i></a>
          <h5>Ángel Pacheco</h5>
          <p><em>Chief Marketing Officer (CMO)</em></p>
          <p>Ingeniero Civil de la Universidad Católica Andrés Bello y MBA de la Escuela de Organizacion Industrial, España.
          Responsable del desarrollo de negocios para el Ministerio de la Defensa en ALCATEL (1998), Key Account Manager en LogicaCMG para el Mercado de Centro América y responsable de la unidad de compras técnicas en Digitel TIM, Senior Account Manager en ZTE, responsable ejecutivo de la cuenta de CANTV en Nokia Siemens Network.
          Fundó Divux en el 2007, encargado del desarrollo de la estrategia de expansión en el Mercado Latinoamericano. Responsable de la creación y la ampliación de las alianzas estratégicas. Supervisa las operaciones de ingreso y desarrollo de negocios, así como la comercialización y la creación de alianzas.
          </p>
        </div>
         <div class="boss">
          <a href="http://www.linkedin.com/in/alejandromarius" target="_blank" >LinkedIn Alejandro
          <i></i></a>
          <h5>Alejandro Marius</h5>
          <p><em>Asesor Externo</em></p>
          <p>Magister en Sistemas e Ingeniero Electrónico USB. Experiencia en las TIC´s desde 1993, desde 2003 responsable de desarrollar negocios y start-up de empresas españolas e italianas en LATAM. Emprendedor social, Presidente y Fundador de la Asociación Civil Trabajo y Persona. Presidente de la Asociación CDO Venezuela y Miembro de la directiva de la Cámara Venezolano Italiana (CAVENIT).
          </p>
        </div>
    </div>
  </div>

  <div class="foundations">
    <div class="container">
      <div class="row">
        <div class="span6">
          <h2>Todo nuestro trabajo y 
              crecimiento de nuestra 
              gente está fundamentado en:
          </h2>
        </div>

        <div class="span6">
          <%= image_tag 'about-us/img-zapata.png', alt: 'Responsabilidad, Solidaridad, Compromiso, Honestidad, Compañerismo' %>
        </div>
      </div>
    </div>
  </div>

  <div class="social-responsibility">
    <div class="container">
      <div class="row">
        <div class="span4">
          <h2>Responsabilidad Social</h2>

          <p>
            Para nosotros la Responsabilidad
            Social es un pilar fundamental de
            nuestra empresa, no concebimos
            nuestro trabajo sin reconocernos
            responsables por el impacto que
            nuestra empresa tiene en la
            construcción de una mejor sociedad
            y del bien común.
          </p>
        </div>

        <div class="span8">
          <div class="project">
            <div id="contact-carousel" class="carousel slide">
              <div class="carousel-inner">
                <% 1.upto(3) do |index| %>
                  <div class="<%= 'active' if index == 1 %> item">
                    <%= render partial: "company_#{index}" %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
          <div class="arrows pull-right">
            <a class="carousel-control left" href="#contact-carousel" data-slide="prev">
              <%= image_tag 'about-us/arrow-left.png', alt: '&rsaquo;' %>
            </a>
            <a class="carousel-control right" href="#contact-carousel" data-slide="next">
              <%= image_tag 'about-us/arrow-right.png', alt: '&rsaquo;' %>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/contact/index.html.erb
<div class="contact">
  <div class="header">
    <div class="container">
      <h1>Contactos</h1>
    </div>
  </div>

  <div class="summary">
    <div class="container">
      <h2>Para comunicarte con nosotros</h2>

      <p>
        Av. Rómulo Gallegos con Calle el Carmen, Centro Dos Caminos, piso 8, oficina 8-D. Caracas. Venezuela.<br>
        / Teléfonos: (+58) 212 238.07.80 / Email: <a class="mail" href="mailto:info@divux.com">info@divux.com</a><br>
        <strong>Si te interesa mas información sobre nuestros productos y servicios: <a class="mail" href="mailto:servicios@divux.com">servicios@divux.com</a></strong>
      </p>

       <h2>Síguenos en</h2>

      <div class="syndication">
        <%= link_to '&nbsp;'.html_safe, 'https://www.facebook.com/DivuxSystems', class: 'facebook', :target => '_blank' %>
        <%= link_to '&nbsp;'.html_safe, 'https://twitter.com/DivuxVe', class: 'twitter', :target => '_blank' %>
        <%= link_to '&nbsp;'.html_safe, 'http://www.linkedin.com/company/695479', class: 'linkedin', :target => '_blank' %>
     </div>
    </div>
  </div>

app/views/jobs/index.html.erb
<div class="job-detail">
  <div class="header">
    <div class="container">
      <h1>Empleo</h1>
    </div>
  </div>

  <div class="container">
    <div class="span11">
      <p class="title">
        Buscamos personas jóvenes, con deseo de aprender e innovar para ser parte de un equipo de alto nivel técnico y con grandes perspectivas de crecimiento y desarrollo.
      </p>
    </div>
    <% @jobs.each do |job| %>
      <div class="span5">
        <h4><%= job.title %></h4>
        <% if job.id == 2 %>
          <%= image_tag 'portfolio/ico-movil.png' %>
        <% end %>
        <%= image_tag 'portfolio/ico-web.png' %>
        <p><%= simple_format job.description %></p>
        <p>Envíanos tu curriculum a: <%= mail_to 'reclutamiento@divux.com' %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Divux Systems</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container-fluid">
  <div class="layout-header">
    <div class="container">
      <%= link_to root_path do %>
        <%= image_tag 'layout/logo-divux-nav.png' %>
      <% end %>

      <ul class="nav nav-pills pull-right hidden-tablet hidden-phone">
        <li><%= link_to 'Nosotros',  company_path, class: menu_item_class(:company) %></li>
        <li><%= link_to 'Servicios', services_path, class: menu_item_class(:services) %></li>
        <li><%= link_to 'Productos', products_path, class: menu_item_class(:products) %></li>
        <li><%= link_to 'Experiencia', portfolio_index_path, class: menu_item_class(:portfolio) %></li>
        <li><%= link_to 'Contactos', contact_index_path, class: menu_item_class(:contact) %></li>
      </ul>

      <div class="btn-group pull-right hidden-desktop">
        <a class="btn btn-link dropdown-toggle" data-toggle="dropdown">Menú <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to 'Nosotros',  company_path, class: menu_item_class(:company) %></li>
          <li><%= link_to 'Servicios', services_path, class: menu_item_class(:services) %></li>
          <li><%= link_to 'Productos', products_path, class: menu_item_class(:products) %></li>
          <li><%= link_to 'Experiencia', portfolio_index_path, class: menu_item_class(:portfolio) %></li>
          <li><%= link_to 'Contactos', contact_index_path, class: menu_item_class(:contact) %></li>    
        </ul>
     </div>
    </div>
  </div>

  <%= yield %>
  
  <div class="layout-footer">
    <div class="border">
    </div>
    <div class="container">
      <div class="row">
        <div class="span4">
          <div class="jobs">
            <h3>Únete a nuestro equipo</h3>
            <h4 class="title">Buscamos:</h4>

            <% Job.limit(2).each do |job| %>
              <div class="job">
                <h4><%= job.title %></h4>

                <p><%= job.summary %></p>

                <%= link_to '', jobs_index_path %>
              </div>
            <% end %>
          </div>
        </div>

        <div class="span4">
          <div class="syndication">
            <%= link_to '&nbsp;'.html_safe, 'https://www.facebook.com/DivuxSystems', class: 'facebook', :target => '_blank' %>
            <%= link_to '&nbsp;'.html_safe, 'https://twitter.com/DivuxVe', class: 'twitter', :target => '_blank' %>
            <%= link_to '&nbsp;'.html_safe, 'http://www.linkedin.com/company/695479', class: 'linkedin', :target => '_blank' %>
          </div>

          <% Tweet.last(2).each do |tweet| %>
            <div class="latest-tweet">
              <div class="tweet">
                <%= tweet.content %>
              </div>
            </div>
          <% end %>

        </div>
        <div class="span4">
          <ul class="nav">
            <li><%= link_to '/ Nosotros',  company_path %></li>
            <li><%= link_to '/ Servicios', services_path %></li>
            <li><%= link_to '/ Productos', products_path %></li>
            <li><%= link_to '/ Experiencia', portfolio_index_path %></li>
            <li><%= link_to '/ Empleo', jobs_index_path %></li>
            <li><%= link_to '/ Contactos', contact_index_path %></li>
            <li class="mail"><%= mail_to 'info@divux.com' %></li>
          </ul>

          <div class="copyright">
            <p>
              &copy; <%= Time.now.year %> - DIVUX SYSTEMS, C.A.<br/>
              RIF J-29546313-8
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-41205244-3', 'divux.com');
  ga('send', 'pageview');

</script>

</body>
</html>

app/views/portfolio/index.html.erb
<div class="portfolio">
  <div class="header">
    <div class="container">
      <h1>Experiencia</h1>
    </div>
  </div>

  <div class="projects">
    <div class="container">

      <div class="row">
        <div class="span4">
          <div class="portfolio-item">
            <%= link_to '&nbsp'.html_safe, portfolio_chacao_path, class: 'image chacao' %>
          </div>
        </div>

        <div class="span4">
          <div class="portfolio-item">
            <%= link_to '&nbsp'.html_safe, portfolio_shick_path, class: 'image shick' %>
          </div>
        </div>

        <div class="span4">
          <div class="portfolio-item">
            <%= link_to '&nbsp'.html_safe, portfolio_cnti_path, class: 'image cnti' %>
          </div>
        </div>
      </div>

    </div>
  </div>

  <div class="our-scope">
    <div class="container">
      <div class="row">
        <div class="span4">
          <h2>Nuestro Alcance</h2>

          <p>
            Nuestros productos y servicios han sido diseñados para llegar a diferentes culturas, esto nos ha permitido tener una presencia Internacional. Contamos con un equipo creativo e innovador capacitado continuamente en las nuevas tendencias de tecnología. 
          </p>
        </div>

        <div class="span8">
          <%= image_tag 'portfolio/scope/img-map.png' %>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/welcome/index.html.erb
<div class="home">

  <div class="featured">
      <div id="header-carousel" class="carousel slide" data-interval="2000">
          <div class="carousel-inner">
            <div class="item active">
              <div class="header-item header-1">
                  <div class="info info-1">
                
                  </div>
              </div> 
            </div>
            <div class="item">
              <div class="header-item header-2">
                <div class="info info-2">
                  </div>
              </div> 
            </div>
             <div class="item">
              <div class="header-item header-3">
                <div class="info info-3">
                  </div>
              </div> 
            </div>        
        </div>
      </div>
  </div>

  <div class="main-sections">
    <div class="container">
      <div class="row">
        <div class="span4">
          <h2>Servicios</h2>

          <%= link_to '&nbsp'.html_safe, services_path, class: 'services' %>

          <p>
            Ofrecemos soluciones que se adaptan a
            las necesidades teconológicas de tu
            empresa.
          </p>
        </div>

        <div class="span4">
          <h2>Productos</h2>

          <%= link_to '&nbsp'.html_safe, products_path, class: 'products' %>

          <p>
            Construimos herramientas para el
            desarrollo de prototipos en Android
            y HTML5 (MoB).
          </p>
        </div>

        <div class="span4">
          <h2>¿Cómo trabajamos?</h2>

          <%= link_to '&nbsp'.html_safe, services_path(anchor: 'how-we-work'), class: 'how-we-work' %>

          <p>
            Desde la identificación de la necesidad
            hasta la puesta en producción y el
            posterior mantenimiento.
          </p>
        </div>
      </div>
    </div>
  </div>

  <div class="portfolio">
    <div class="container">
      <div class="row">
        <div class="span4">
          <h2>Nuestra Experiencia</h2>

          <p>
            Hemos desarrollado soluciones complejas y simples para pequeñas y grandes empresas en sectores como: consumo masivo, comercio, telecom, público, educativo, entre otros.
          </p>
        </div>

    <div class="span8">
      <div id="our-experience-carousel" class="carousel slide">
        <div class="carousel-inner">
          <div class="item active">
            <div class="portfolio-item">
                <%= link_to '&nbsp'.html_safe, portfolio_cnti_path, class: 'image cnti' %>
            </div>    
            <div class="portfolio-item">
                <%= link_to '&nbsp'.html_safe, portfolio_shick_path, class: 'image shick' %>
            </div>
          </div>
          <div class="item">
            <div class="portfolio-item">
              <%= link_to '&nbsp'.html_safe, portfolio_chacao_path, class: 'image chacao' %>
            </div>
          </div>
        </div>
        <a class="carousel-control left" href="#our-experience-carousel" data-slide="prev">
          <%= image_tag 'home/arrow-left.png', alt: '&lsaquo;' %>
        </a>
        <a class="carousel-control right" href="#our-experience-carousel" data-slide="next">
          <%= image_tag 'home/arrow-right.png', alt: '&rsaquo;' %>
        </a>
      </div>
    </div>

      </div>
    </div>
  </div>

  <div class="clients">
    <div class="container">
      <div class="row">
        <h2>Clientes</h2>

        <div class="logos">
          <%= image_tag 'home/cnti.png' %>
          <%= image_tag 'home/educa.png' %>
          <%= image_tag 'home/genexies.png' %>
          <%= image_tag 'home/chacao.png' %>
          <%= image_tag 'home/schick.png' %>
          <%= image_tag 'home/visalock.png' %>
          <%= image_tag 'home/masisa.png' %>
          <%= image_tag 'home/infosoft.png' %>
          <%= image_tag 'home/frufru.png' %>
          <%= image_tag 'home/quantum.png' %>
           <!--
          <%= image_tag 'home/pns.jpg' %>      
          -->
        </div>
      </div>
    </div>
  </div>

</div>